[project]
name = "prefect-flows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect>=3.0.10",
    "httpx[socks]>=0.27.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
